[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/es/"
  status = 302

[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/fr/*"
  to = "/fr/index.html"
  status = 200

[[redirects]]
  from = "/ca/*"
  to = "/ca/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"